version: '3.4'

services:
  node1:
    image: lightning:v0.7.3
    entrypoint: bash -c "sleep 2 && bitcoind -daemon -connect=node2 -regtest && sleep 2 && lightningd --network=regtest"
    hostname: node1
    ports:
      - "5005:5005"
    volumes:
      - ~/.m2:/root/.m2
      - ../../:/root/project
    depends_on:
      - node2
    networks:
      - regtest
    container_name: node1

  node2:
    image: lightning:v0.7.3
    entrypoint: bash -c "bitcoind -daemon -regtest && sleep 2 && lightningd --network=regtest"
    hostname: node2
    ports:
      - "5006:5005"
    volumes:
      - ~/.m2:/root/.m2
      - ../../:/root/project
    networks:
      - regtest
    container_name: node2

networks:
  regtest: 
